 language: java
 jdk:
   - openjdk17

before_deploy:
   - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 2.1.0
deploy:
   provider: heroku
   api_key:
      secure: $HEROKU_TOKEN
   app: "book-store-hellmann"